# Welcome to Jekyll!
#

# Site settings
title: Bajki dookoła
description: |
  Już nie za siedmioma górami,  
  już nie za siedmioma lasami,  
  ale tutaj,
  w Twoim hotelu
owner: Bajki dookoła # or company name
first_published: 2023 # if migrating another site, the year of your first publish
email: kontakt@bajkidookola.pl
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bajkidookla.pl" # the base hostname & protocol for your site
social:
#  twitter: https://twitter.com/<username>
#  github: https://github.com/<username>
#  linkedin-square: https://linkedin.com/in/<username>
#  facebook-official: https://facebook.com/<username>
#  google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:kontakt@bajkidookola.pl
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
